spring.application.name=cloudshareapi
spring.data.mongodb.uri=mongodb+srv://vikaschaudhary7474_db_user:kKPKB7LuUmybWsIO@cluster0.e7a2gwi.mongodb.net/cloudshare?appName=Cluster0
server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
clerk.issuer=https://relieved-mouse-70.clerk.accounts.dev
clerk.jwks-url=https://relieved-mouse-70.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_y9VWBFYnK9Eo2izRF3DPbre7OgOC9v2P
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
razorpay.key.id=rzp_test_SNrhCuRcrLYzsR
razorpay.key.secret=7DTHp3RtKJ4LrHv2LmSnqRwp
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
